[package]
name = "bathbot-twilight"
version = "2.4.6"
authors = ["MaxOhn <ohn.m@hotmail.de>"]
edition = "2021"

[dependencies]
bb8-redis = { version = "0.11" }
bitflags = { version = "1.0" }
bytes = { version = "1.0" }
command-macros = { path = "./command-macros" }
dotenv = { version = "0.15" }
enterpolation = { version = "0.1", default-features = false, features = ["std", "linear"] }
eyre = { version = "0.6" }
flexmap = { git = "https://github.com/MaxOhn/flexmap" }
flurry = { version = "0.4" }
futures = { version = "0.3", default-features = false }
handlebars = { version = "4.0" }
hashbrown = { version = "0.12", features = ["serde"] }
http = { version = "0.2" }
hyper = { version = "0.14", default-features = false, features = ["server"] }
hyper-rustls = { version = "0.23", default-features = false, features = ["http1", "tls12", "tokio-runtime", "webpki-tokio"] }
image = { version = "0.24", default-features = false, features = ["gif", "png"] }
itertools = { version = "0.10" }
leaky-bucket-lite = { version = "0.5", features = ["parking_lot"] }
once_cell = { version = "1.0" }
parking_lot = { version = "0.12", default-features = false }
plotters = { version = "0.3", default-features = false, features = ["bitmap_backend", "image", "line_series", "area_series", "histogram", "point_series"] }
plotters-backend = { version = "0.3" }
priority-queue = { version = "1.0", optional = true }
prometheus = { version = "0.13" }
radix_trie = { version = "0.2" }
rand = { version = "0.8" }
regex = { version = "1.0" }
rkyv = { version = "0.7" }
rosu-v2 = { git = "https://github.com/MaxOhn/rosu-v2", branch = "next", features = ["cache", "metrics", "rkyv"] }
# rosu-v2 = { path = "../rosu-v2", features = ["cache", "metrics", "rkyv"] }
rosu-pp = { git = "https://github.com/MaxOhn/rosu-pp", branch = "next", features = ["async_tokio"] }
# rosu-pp = { path = "../rosu-pp" }
rosu-pp-older = { git = "https://github.com/MaxOhn/rosu-pp-older.git", branch = "main" }
# rosu-pp-older = { path = "../rosu-pp-older" }
routerify = { version = "3.0", optional = true }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_cbor = { version = "0.11", default-features = false, features = ["std"] }
serde_json = { version = "1.0" }
serde_urlencoded = { version = "0.7" }
smallstr = { version = "0.2", features = ["serde"] }
smallvec = { version = "1.0", features = ["serde"] }
sqlx = { version = "0.6", default-features = false, features = ["json", "macros", "migrate", "postgres", "runtime-tokio-rustls", "time"] }
thiserror = { version = "1.0" }
time = { version = "0.3", features = ["parsing"] }
tokio = { version = "1.20", default-features = false, features = ["fs", "io-util", "macros", "parking_lot", "rt-multi-thread", "signal", "sync", "time"] }
tokio-stream = { version = "0.1", default-features = false }
tracing = { version = "0.1" }
tracing-appender = { version = "0.2" }
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt", "smallvec", "std", "time", "tracing-log"] }

# twilight-gateway = { path = "../twilight/twilight-gateway" }
# twilight-cache-inmemory = { path = "../twilight/twilight-cache-inmemory/", default-features = false }
# twilight-http = { path = "../twilight/twilight-http", default-features = false, features = ["rustls-webpki-roots"] }
# twilight-interactions = { path = "../twilight-interactions/twilight-interactions", default-features = false, features = ["derive"] }
# twilight-model = { path = "../twilight/twilight-model", default-features = false }
# twilight-standby = { path = "../twilight/twilight-standby", default-features = false }
# twilight-validate = { path = "../twilight/twilight-validate" }

twilight-gateway = { git = "https://github.com/MaxOhn/twilight", branch = "rkyv-13" }
twilight-cache-inmemory = { git = "https://github.com/MaxOhn/twilight", branch = "rkyv-13", default-features = false }
twilight-http = { git = "https://github.com/MaxOhn/twilight", branch = "rkyv-13", default-features = false, features = ["rustls-webpki-roots"] }
twilight-interactions = { git = "https://github.com/MaxOhn/twilight-interactions", branch = "rkyv-13", default-features = false, features = ["derive"] }
twilight-model = { git = "https://github.com/MaxOhn/twilight", branch = "rkyv-13", default-features = false }
twilight-standby = { git = "https://github.com/MaxOhn/twilight", branch = "rkyv-13", default-features = false }
twilight-validate = { git = "https://github.com/MaxOhn/twilight", branch = "rkyv-13" }

[profile.dev.package.sqlx-macros]
opt-level = 3

[profile.release]
lto = "thin"
codegen-units = 1
strip = "debuginfo"

[features]
default = ["offline"]
full = ["global_slash", "matchlive", "osutracking", "server", "twitch", "twitchtracking"]

global_slash = []
matchlive = []
offline = ["sqlx/offline"]
osutracking = ["priority-queue"]
server = ["routerify", "twitch"]
twitch = []
twitchtracking = ["twitch"]
