[workspace]

members = [
    "bathbot",
    "bathbot-macros",
    "bathbot-psql",
]

[profile.dev.package.sqlx-macros]
opt-level = 3

[profile.release]
lto = "thin"
codegen-units = 1
strip = "debuginfo"