[package]
name = "bathbot-twilight"
version = "0.1.0"
authors = ["MaxOhn <ohn.m@hotmail.de>"]
edition = "2018"

[dependencies]
async-trait  = "0.1"
bitflags     = "1.2"
bytes        = "1.0"
futures      = "0.3"
governor     = "0.3"
itertools    = "0.10"
lazy_static  = "1.4"
log          = "0.4"
once_cell    = "1.4"
priority-queue = "1.0"
proc_macros  = { path = "./proc_macros" }
prometheus   = "0.12"
radix_trie   = "0.2"
rand         = "0.8"
regex        = "1.5"
serde_json   = "1.0"
strfmt       = "0.1.6"
toml         = "0.5"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.dashmap]
version = "4.0"
features = ["serde"]

[dependencies.deadpool-redis]
version = "0.9"
default-features = false
features = ["rt_tokio_1"]

[dependencies.dotenv]
version = "0.15"

[dependencies.flexi_logger]
version = "0.18"
default_features = false
features = ["colors", "specfile", "compress"]

[dependencies.hashbrown]
version = "0.11"
features = ["serde"]

[dependencies.hyper]
version = "0.14"
default_features = false
features = ["server"]

[dependencies.image]
version = "0.23"
default-features = false
features = ["png", "gif"]

[dependencies.parking_lot]
version = "0.11"
default-features = false
features = ["send_guard"]

[dependencies.plotters]
version = "0.3"
default-features = false
features = ["bitmap_backend", "image", "line_series", "datetime", "area_series", "histogram"]

[dependencies.reqwest]
version = "0.11"
default_features = false
features = ["cookies", "multipart", "rustls-tls-native-roots"]

[dependencies.rosu-v2]
git = "https://github.com/MaxOhn/rosu-v2"
branch = "next"
# path = "../rosu-v2"
features = ["cache", "metrics"]

[dependencies.rosu-pp]
git = "https://github.com/MaxOhn/rosu-pp"
branch = "next"
features = ["async_tokio"]

[dependencies.rosu-pp-newer]
# path = "../rosu_v2-pp-newer"
git = "https://github.com/MaxOhn/rosu-pp-newer.git"
branch = "main"

[dependencies.rosu-pp-older]
# path = "../rosu_v2-pp-older"
git = "https://github.com/MaxOhn/rosu-pp-older.git"
branch = "main"

[dependencies.serde]
version = "1.0"
features = ["derive", "rc"]

[dependencies.serde_cbor]
version = "0.11"
default_features = false
features = ["std"]

[dependencies.smallstr]
version = "0.2"
features = ["serde"]

[dependencies.smallvec]
version = "1.6"
features = ["serde"]

[dependencies.sqlx]
version = "0.5"
default-features = false
features = ["chrono", "json", "macros", "migrate", "postgres", "runtime-tokio-native-tls"]

[dependencies.tokio]
version = "1.6"
default_features = false
features = ["fs", "io-util", "macros", "rt-multi-thread", "signal", "sync", "time"]

[dependencies.tokio-stream]
version = "0.1.2"
default_features = false

[dependencies.twilight-cache-inmemory]
# path = "../twilight/cache/in-memory"
branch = "with_redis"
git = "https://github.com/MaxOhn/twilight"

[dependencies.twilight-gateway]
# path = "../twilight/gateway"
branch = "with_redis"
git = "https://github.com/MaxOhn/twilight"

[dependencies.twilight-http]
# path = "../twilight/http"
branch = "with_redis"
git = "https://github.com/MaxOhn/twilight"
default_features = false
features = ["rustls"]

[dependencies.twilight-model]
# path = "../twilight/model"
branch = "with_redis"
git = "https://github.com/MaxOhn/twilight"
default_features = false

[dependencies.twilight-standby]
# path = "../twilight/standby"
branch = "with_redis"
git = "https://github.com/MaxOhn/twilight"
default_features = false

[features]
vendored-openssl = ["openssl/vendored"]

[dependencies.openssl]
version = "0.10"
optional = true
