[package]
name = "bathbot-twilight"
version = "0.1.0"
authors = ["MaxOhn <ohn.m@hotmail.de>"]
edition = "2018"

[dependencies]
bitflags    = "1.2"
clap        = "2.33"
chrono      = "0.4"
ctrlc       = { version = "3.1", features = ["termination"] }
dashmap     = { version = "4.0.0-rc6", features= ["serde"] }
darkredis   = "0.7"
futures     = "0.3"
lazy_static = "1.4"
log         = "0.4"
once_cell   = "1.4"
prometheus  = "0.8"
refinery    = { version= "0.2", features=["tokio-postgres"] }
regex       = "1.3"
rosu        = "0.2"
serde       = { version = "1.0", features = ["derive", "rc"] }
serde_json  = "1.0"
tokio       = { version = "0.2", default_features = false, features = ["macros", "sync", "rt-core"] }
twilight    = { git="https://github.com/twilight-rs/twilight", branch = "trunk" }
toml        = "0.5"
warp        = "0.2"

[dependencies.deadpool-postgres]
version  = "0.5"
features = [ "config" ]

[dependencies.flexi_logger]
version = "0.15"
default_features = false
features = [ "colors", "specfile", "ziplogs" ]

[dependencies.postgres-types]
version = "0.1"
features = [ "with-serde_json-1" ]

[dependencies.tokio-postgres]
version          = "0.5"
default-features = false
#features = [ "with-chrono-0_4" ]
