[package]
name = "bathbot-twilight"
version = "0.1.0"
authors = ["MaxOhn <ohn.m@hotmail.de>"]
edition = "2018"

[dependencies]
failure = "0.1"
flexi_logger = { version = "0.15", default_features = false, features = ["colors", "specfile", "ziplogs"] }
git-version  = "0.3"
lazy_static  = "1.4"
log          = "0.4"
once_cell    = "1.4"
tokio        = { version = "0.2", default_features = false, features = ["macros", "sync", "rt-core"] }
twilight     = { git="https://github.com/twilight-rs/twilight", branch = "trunk" }