[package]
name = "bathbot-twilight"
version = "0.1.0"
authors = ["MaxOhn <ohn.m@hotmail.de>"]
edition = "2018"

[build-dependencies.cc]
version = "1.0"
features = ["parallel"]

[build-dependencies.bindgen]
version = "0.55"

[dependencies]
async-trait  = "0.1"
bitflags     = "1.2"
bytes        = "0.6"
chrono       = "0.4"
cow-utils    = "0.1"
darkredis    = "0.7"
futures      = "0.3"
governor     = "0.3"
itertools    = "0.9"
lazy_static  = "1.4"
log          = "0.4"
once_cell    = "1.4"
priority-queue = "1.0"
proc_macros  = { path = "./proc_macros" }
prometheus   = "0.10"
radix_trie   = "0.2"
rand         = "0.7"
rayon        = "1.3"
regex        = "1.3"
serde_json   = "1.0"
strfmt       = "0.1.6"
sysinfo      = "0.11"
toml         = "0.5"
uwl          = "0.6"

[dependencies.clap]
version = "2.33"
default_features = false

[dependencies.dashmap]
version = "3.11"
features = ["serde"]

[dependencies.flexi_logger]
version = "0.16"
default_features = false
features = ["colors", "specfile", "compress"]

[dependencies.hyper]
version = "0.13"
default_features = false

[dependencies.image]
version = "0.23"
default-features = false
features = ["png", "gif"]

[dependencies.openssl]
version = "0.10"
optional = true

[dependencies.plotters]
version = "0.3"
default-features = false
features = ["bitmap_backend", "image", "line_series", "datetime", "area_series", "histogram"]

[dependencies.reqwest]
version = "0.10"
default_features = false
features = ["cookies"]

[dependencies.rosu]
# version = "0.4"
git = "https://github.com/MaxOhn/rosu"
branch = "master"
features = ["cache", "metrics"]

[dependencies.rosu-pp]
# path = "../rosu-pp"
git = "https://github.com/MaxOhn/rosu-pp"
branch = "main"

[dependencies.scraper]
version = "0.12"
default-features = false

[dependencies.serde]
version = "1.0"
features = ["derive", "rc"]

[dependencies.sqlx]
version = "0.4"
default-features = false
features = ["postgres", "runtime-tokio-rustls", "chrono", "macros", "json"]

[dependencies.tokio]
version = "0.2"
default_features = false
features = ["fs", "io-util", "macros", "process", "signal", "stream", "sync", "time"]

[dependencies.twilight-cache-inmemory]
# path = "../twilight/cache/in-memory"
branch = "custom-cache"
git = "https://github.com/MaxOhn/twilight"

[dependencies.twilight-embed-builder]
# path = "../twilight/embed-builder"
branch = "custom-cache"
git = "https://github.com/MaxOhn/twilight"
default_features = false

[dependencies.twilight-gateway]
# path = "../twilight/gateway
branch = "custom-cache"
git = "https://github.com/MaxOhn/twilight"

[dependencies.twilight-http]
# path = "../twilight/http"
branch = "custom-cache"
git = "https://github.com/MaxOhn/twilight"
default_features = false
features = ["rustls"]

[dependencies.twilight-model]
# path = "../twilight/model"
branch = "custom-cache"
git = "https://github.com/MaxOhn/twilight"
default_features = false

[dependencies.twilight-standby]
# path = "../twilight/standby"
branch = "custom-cache"
git = "https://github.com/MaxOhn/twilight"
default_features = false

[features]
vendored-openssl = ["openssl/vendored"]