[package]
name = "bathbot-twilight"
version = "0.1.0"
authors = ["MaxOhn <ohn.m@hotmail.de>"]
edition = "2018"

[build-dependencies]
cc      = { version = "1.0", features = ["parallel"] }

[build-dependencies.bindgen]
version = "0.54"
default_features = false

[dependencies]
async-trait = "0.1"
bitflags    = "1.2"
bytes       = "0.5"
chrono      = "0.4"
darkredis   = "0.7"
futures     = "0.3"
lazy_static = "1.4"
log         = "0.4"
once_cell   = "1.4"
proc_macros = { path = "./proc_macros" }
prometheus  = "0.9"
radix_trie  = "0.2"
regex       = "1.3"
serde_json  = "1.0"
static_assertions = "1.1"
toml        = "0.5"
uwl         = "0.6"

[dependencies.clap]
version = "2.33"
default_features = false

[dependencies.ctrlc]
version = "3.1"
features = ["termination"]

[dependencies.dashmap]
version = "4.0.0-rc6"
features = ["serde"]

[dependencies.rosu]
git = "https://github.com/MaxOhn/rosu"
branch = "serialize"
features = [ "serialize" ]

[dependencies.flexi_logger]
version = "0.15"
default_features = false
features = ["colors", "specfile", "ziplogs"]

[dependencies.serde]
version = "1.0"
features = ["derive", "rc"]

[dependencies.sqlx]
git              = "https://github.com/launchbadge/sqlx/"
branch           = "master"
default-features = false
features         = ["postgres", "runtime-tokio", "chrono", "macros", "json"]

[dependencies.tokio]
version = "0.2"
default_features = false
features = ["macros", "sync", "rt-core"]

[dependencies.twilight-builders]
git = "https://github.com/twilight-rs/twilight"
branch = "trunk"
default_features = false

[dependencies.twilight-gateway]
git = "https://github.com/twilight-rs/twilight"
branch = "trunk"
default_features = false
features = ["serde_json"]

[dependencies.twilight-http]
git = "https://github.com/twilight-rs/twilight"
branch = "trunk"
default_features = false
features = ["rustls"]

[dependencies.twilight-mention]
git = "https://github.com/twilight-rs/twilight"
branch = "trunk"
default_features = false

[dependencies.twilight-model]
git = "https://github.com/twilight-rs/twilight"
branch = "trunk"
default_features = false

[dependencies.twilight-standby]
git = "https://github.com/twilight-rs/twilight"
branch = "trunk"
default_features = false

[dependencies.warp]
version = "0.2"
default_features = false
features = ["tls"]
