[package]
name = "bathbot-twilight"
version = "0.1.0"
authors = ["MaxOhn <ohn.m@hotmail.de>"]
edition = "2021"

[dependencies]
async-trait = { version = "0.1" }
bb8-redis = { version = "0.10" }
bitflags = { version = "1.0" }
bytes = { version = "1.0" }
chrono = { version = "0.4", features = ["serde"] }
dashmap = { version = "4.0", features = ["serde"] }
dotenv = { version = "0.15" }
eyre = { version = "0.6" }
futures = { version = "0.3" }
governor = { version = "0.3" }
handlebars = { version = "4.0" }
hashbrown = { version = "0.12", features = ["serde"] }
hyper = { version = "0.14", default-features = false, features = ["server"] }
hyper-rustls = { version = "0.23", default-features = false, features = ["http1", "tls12", "tokio-runtime", "webpki-tokio"] }
image = { version = "0.23", default-features = false, features = ["png", "gif"] }
itertools = { version = "0.10" }
lazy_static = { version = "1.0" }
once_cell = { version = "1.0" }
parking_lot = { version = "0.12", default-features = false }
plotters = { version = "0.3", default-features = false, features = ["bitmap_backend", "image", "line_series", "datetime", "area_series", "histogram"] }
priority-queue = { version = "1.0" }
proc_macros  = { path = "./proc_macros" }
prometheus = { version = "0.13" }
radix_trie = { version = "0.2" }
rand = { version = "0.8" }
regex = { version = "1.0" }
reqwest = { version = "0.11", default-features = false, features = ["cookies", "multipart", "rustls-tls"] }
rkyv = { version = "0.7" }
rosu = { version = "0.5" }
rosu-v2 = { git = "https://github.com/MaxOhn/rosu-v2", branch = "next", features = ["cache", "metrics", "rkyv"] }
# rosu-v2 = { path = "../rosu-v2", features = ["cache", "metrics", "rkyv"] }
rosu-pp = { git = "https://github.com/MaxOhn/rosu-pp", branch = "next", features = ["async_tokio"] }
# rosu-pp = { path = "../rosu-pp" }
rosu-pp-older = { git = "https://github.com/MaxOhn/rosu-pp-older.git", branch = "main" }
# rosu-pp-older = { path = "../rosu-pp-older" }
routerify = { version = "3.0" }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_cbor = { version = "0.11", default-features = false, features = ["std"] }
serde_json = { version = "1.0" }
smallstr = { version = "0.2", features = ["serde"] }
smallvec = { version = "1.0", features = ["serde"] }
sqlx = { version = "0.5", default-features = false, features = ["chrono", "json", "macros", "migrate", "postgres", "runtime-tokio-rustls"] }
thiserror = { version = "1.0" }
time = { version = "0.3", features = ["macros", "parsing"] }
tokio = { version = "1.0", default-features = false, features = ["fs", "io-util", "macros", "rt-multi-thread", "signal", "sync", "time"] }
tokio-stream = { version = "0.1", default-features = false }
toml = { version = "0.5" }
tracing = { version = "0.1" }
tracing-appender = { version = "0.2" }
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt", "smallvec", "std", "time", "tracing-log"] }
# twilight-gateway = { version = "0.9" }
# twilight-cache-inmemory = { version = "0.9", default-features = false }
# twilight-http = { version = "0.9", default-features = false, features = ["rustls-webpki-roots"] }
# twilight-model = { version = "0.9", default-features = false }
# twilight-standby = { version = "0.9", default-features = false }
# twilight-validate = { version = "0.9" }

# twilight-gateway = { path = "../twilight/gateway" }
# twilight-cache-inmemory = { path = "../twilight/cache/in-memory", default-features = false }
# twilight-http = { path = "../twilight/http", default-features = false, features = ["rustls-webpki-roots"] }
# twilight-model = { path = "../twilight/model", default-features = false }
# twilight-standby = { path = "../twilight/standby", default-features = false }
# twilight-validate = { path = "../twilight/validate" }

twilight-gateway = { git = "https://github.com/MaxOhn/twilight", branch = "rkyv" }
twilight-cache-inmemory = { git = "https://github.com/MaxOhn/twilight", branch = "rkyv", default-features = false }
twilight-http = { git = "https://github.com/MaxOhn/twilight", branch = "rkyv", default-features = false, features = ["rustls-webpki-roots"] }
twilight-model = { git = "https://github.com/MaxOhn/twilight", branch = "rkyv", default-features = false }
twilight-standby = { git = "https://github.com/MaxOhn/twilight", branch = "rkyv", default-features = false }
twilight-validate = { git = "https://github.com/MaxOhn/twilight", branch = "rkyv" }
