bg_path = "path/to/bg/folder"

[tokens]
discord = ""
osu = ""
osu_session = ""
twitch_client_id = ""
twitch_token = ""

[database]
postgres = "postgres://user:password@localhost/db_name"
redis = "localhost:port"