### Optional: Default log level
global_level = 'info'

### Specific log levels per module are optionally defined in this section
[modules]
'bathbot_twilight' = 'debug'
#'mod1' = 'warn'
#'mod2::mod3' = 'trace'
