[package]
name = "proc_macros"
version = "0.1.0"
authors = ["MaxOhn <ohn.m@hotmail.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
static_assertions = "1.1"
quote = "^1.0"
syn = { version = "^1.0", features = ["full", "derive", "extra-traits"] }
proc-macro2 = "^1.0"
