[package]
name = "bathbot-server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6", default-features = false, features = ["http1", "json", "macros", "matched-path", "query", "tokio"] }
bathbot-model = { path = "../bathbot-model" }
bathbot-util = { path = "../bathbot-util" }
eyre = { version = "0.6" }
flexmap = { git = "https://github.com/MaxOhn/flexmap" }
futures = { version = "0.3", default-features = false }
handlebars = { version = "4.0" }
hyper = { version = "0.14", default-features = false, features = ["server"] }
hyper-rustls = { version = "0.23", default-features = false, features = ["http1", "tls12", "tokio-runtime", "webpki-tokio"] }
prometheus = { version = "0.13" }
rosu-v2 = { git = "https://github.com/MaxOhn/rosu-v2", branch = "next", features = ["cache", "metrics", "rkyv"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1.0" }
thiserror = { version = "1.0" }
tokio = { version = "1.0", default-features = false, features = ["sync"] }
tower = { version = "0.4", default-features = false }
tower-http = { version = "0.3", features = ["fs", "trace"] }
tracing = { version = "0.1" }

dotenv = { version = "0.15" }
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt", "smallvec", "std", "time", "tracing-log", "ansi"] }

[dev-dependencies]
tokio = { version = "1.0", default-features = false, features = ["rt-multi-thread", "sync"] }
