name: Run Clippy

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  SQLX_OFFLINE: true

jobs:
  clippy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - kind: no-features
            features: offline
          - kind: full-features
            features: full,offline

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1

      - name: Install SARIF
        run: cargo install clippy-sarif sarif-fmt

      - name: Run clippy
        run: >
          cargo clippy --features ${{ matrix.features }} --message-format=json
          | clippy-sarif
          | tee ${{ matrix.kind }}-clippy-results.sarif
          | sarif-fmt
        continue-on-error: true

      - name: Upload results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ matrix.kind }}-clippy-results.sarif
          wait-for-processing: true
